### PR TITLE
Fix #207

### LINKED ISSUE #207: ns_handle_udp() and async DNS resolver
Reported by Liu Xiaobo:

Hi, I'm testing your fossa library, and I find a bug:
in ns_handle_udp(), you have constructed a ns, which is a copy of ls, and then ns_call() have been called. in ns_call, it maybe routed to ns_resolve_async_eh(), which add a flag to nc:
nc->flags |= NSF_CLOSE_IMMEDIATELY;

and this flag is not synced to ls. that will cause http with async dns failed.

### PR DESCRIPTION
**Pull request by cpq**
Hi @mmikulicic , please make a review

### CODE REVIEW

File: fossa.c [hunk 1]
```diff
@@ -810,19 +810,24 @@ static void ns_handle_udp(struct ns_connection *ls) {
...
     nc.recv_iobuf.buf = buf;
     nc.recv_iobuf.len = nc.recv_iobuf.size = n;
-    nc.sock = ls->sock;
-    nc.handler = ls->handler;
-    nc.user_data = ls->user_data;
-    nc.proto_data = ls->proto_data;
-    nc.proto_handler = ls->proto_handler;
-    nc.mgr = ls->mgr;
     nc.listener = ls;
     nc.flags = NSF_UDP;
```
Comment (mmikulicic) [inline fossa.c]: Why aren't all `ls` flags passed to `nc` ?

**Comment by mmikulicic** [comment]
LGTM
